# Generated by Django 3.2.3 on 2021-05-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_vote', models.TextField()),
                ('second_vote', models.TextField()),
                ('third_vote', models.TextField()),
                ('first_reason', models.TextField()),
                ('second_reason', models.TextField()),
                ('third_reason', models.TextField()),
                ('voter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namemaster')),
            ],
        ),
    ]
